name: votingapp CI

on:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: setup python
              uses: actions/setup-python@v6
              with:
                python-version: '3.12'
            - name: install dependencies
              run: |
                pip install -r vote/requirements.txt
                pip install -r result/requirements.txt
                pip install -r worker/requirements.txt
            - name: Run Vote Tests
              working-directory: vote
              run: |
                pytest tests/test_main.py
            - name: Run result Tests
              working-directory: result
              run: |
                pytest tests/test_main.py
            - name: Run worker Tests
              working-directory: worker
              run: |
                pytest tests/test_main.py

    docker-build:
        needs: build-test
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v6
            - name: Build Result Docker Image
              working-directory: result
              run: |
                docker build -t result .
            - name: Build App Docker Image
              working-directory: vote
              run: |
                docker build -t vote .
            - name: Build Worker Docker Image
              working-directory: worker
              run: |
                docker build -t worker .
    aws-configuration:
        permissions:
            id-token: write
            contents: read

        needs: docker-build
        runs-on: ubuntu-latest
        
        steps:
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                role-to-assume: arn:aws:iam::283609055440:role/Votingapp-Role
                aws-region: us-east-1
            - name: verify aws credentials
              run: |
                aws sts get-caller-identity
                


                


