name: votingapp CI

on:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: setup python
              uses: actions/setup-python@v6
              with:
                python-version: '3.12'
            - name: install dependencies
              run: |
                pip install -r vote/requirements.txt
                pip install -r result/requirements.txt
                pip install -r worker/requirements.txt
            - name: Run Vote Tests
              working-directory: vote
              run: |
                pytest tests/test_main.py
            - name: Run result Tests
              working-directory: result
              run: |
                pytest tests/test_main.py
            - name: Run worker Tests
              working-directory: worker
              run: |
                pytest tests/test_main.py

    docker-build:
        permissions:
            id-token: write
            contents: read
        needs: build-test
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v6
            - name: Build Result Docker Image
              working-directory: result
              run: |
                docker build -t result .
            - name: Build App Docker Image
              working-directory: vote
              run: |
                docker build -t vote .
            - name: Build Worker Docker Image
              working-directory: worker
              run: |
                docker build -t worker .

            - name: Show GitHub OIDC information
              run: |
                echo "Repository: $GITHUB_REPOSITORY"
                echo "Repository owner: $GITHUB_REPOSITORY_OWNER"
                echo "Branch/Ref: $GITHUB_REF"
                echo "Repository ID: $GITHUB_REPOSITORY_ID"
                echo "Repository owner ID: $GITHUB_REPOSITORY_OWNER_ID"
            
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                role-to-assume: arn:aws:iam::283609055440:role/Votingapp-Role
                aws-region: us-east-1
            - name: verify aws credentials
              run: |
                aws sts get-caller-identity

            - name: Login to Amazon ECR
              uses: aws-actions/amazon-ecr-login@v2
            
            - name: Tag and Push Vote Image
              run: |
                docker tag vote 283609055440.dkr.ecr.us-east-1.amazonaws.com/vote:${{ github.sha }}
                docker push 283609055440.dkr.ecr.us-east-1.amazonaws.com/vote:${{ github.sha }}

            - name: Tag and Push Result Image
              run: |
                docker tag result 283609055440.dkr.ecr.us-east-1.amazonaws.com/result:${{ github.sha }}
                docker push 283609055440.dkr.ecr.us-east-1.amazonaws.com/result:${{ github.sha }}

            - name: Tag and Push Worker Image
              run: |
                docker tag worker 283609055440.dkr.ecr.us-east-1.amazonaws.com/worker:${{ github.sha }}
                docker push 283609055440.dkr.ecr.us-east-1.amazonaws.com/worker:${{ github.sha }}            
            
                


                


